### ISSUE TITLE
NeuralNetwork - zapotrzebowanie do GUI

### ISSUE THREAD

**Issue by elohhim** [xelexin/nkolkoikrzyzyk#5]
- Potrzebny jest konstruktor do tworzenia sieci neuronowej z poziomu GUI. Muszę wiedzieć jakie parametry dostarczyć, a nie do końca ogarniam tą klasę.
- Funkcja do ustalenia konkretnej wagi

**Comment by Witek902** [comment]
Done (a76de386227205406bb340de4e50e71dbbf83640, 94559aed4b3229e80c3e9e299dc46820c2bcfd1d).
