### ISSUE TITLE
LookupTable, LookupTablePlayer, dane do treningu

### ISSUE THREAD

**Issue by elohhim** [xelexin/nkolkoikrzyzyk#6]
- LookupTable - klasa reprezentująca tabelę prawdopodobieństw wygranej w zalezności od stanu plaszy. Powinna umożliwic zapis i wczytanie z pliku tak jak w NeuralNetwork.
- LookupTablePlayer - Stworzenie gracza grającego na podstawie tabeli prawdopodobieństw i pozwalającego na jej aktualizację.
- Zebranie danych do treningu sieci

**Comment by Witek902** [comment]
Przydalaby sie opcja pozwalajaca ocenic "stopien nauczenia" sieci, tzn. jak bardzo output sieci pokrywa sie z oczekiwanym (outputem LookupTable).
